---
platform: template
sensors:
  driveway_downlights_power:
    device_class: power
    friendly_name: Driveway Downlights Power
    unit_of_measurement: W
    value_template: >-
      {{
        (states('sensor.driveway_downlight_1_power') | float(0.0)) +
        (states('sensor.driveway_downlight_2_power') | float(0.0)) }}
