---
action:
- service: switch.toggle
  target:
    entity_id: switch.kitchen_powerboard_c
alias: kitchen-controller-powerboard-c-toggle
mode: single
trigger:
- entity_id:
  - sensor.kitchen_controller_action
  from: button_3_single
  platform: state
  to: ""
