---
action:
- service: light.toggle
  target:
    entity_id: light.kitchen_downlights
alias: Switch - Kitchen Downlights
mode: single
trigger:
- entity_id: binary_sensor.kitchen_switch_1
  from: "off"
  platform: state
  to: "on"
- entity_id: binary_sensor.kitchen_switch_2
  from: "off"
  platform: state
  to: "on"
- entity_id: binary_sensor.kitchen_switch_3
  from: "off"
  platform: state
  to: "on"
- entity_id: binary_sensor.kitchen_switch_4
  from: "off"
  platform: state
  to: "on"
