---
cards:
- entity: climate.bedroom_hvac
  type: thermostat
- entities:
  - sensor.bedroom_humidity
  - sensor.bedroom_temperature
  type: entities
columns: 1
square: false
title: Climate
type: grid
