---
cards:
- entities:
  - entities:
    - entity: light.bedroom_downlight_1
      name: Downlight 1
      secondary_info: "{{states('sensor.bedroom_downlight_1_power')}} W"
      type: custom:secondaryinfo-entity-row
    - entity: light.bedroom_downlight_2
      name: Downlight 2
      secondary_info: "{{states('sensor.bedroom_downlight_2_power')}} W"
      type: custom:secondaryinfo-entity-row
    head:
      entity: light.bedroom_downlights
      name: Downlights
      secondary_info: "{{states('sensor.bedroom_downlights_power')}} W"
      type: custom:secondaryinfo-entity-row
    type: custom:fold-entity-row
  - entities:
    - entity: light.bedroom_tablelight_1
      name: Tablelight 1
    - entity: light.bedroom_tablelight_2
      name: Tablelight 2
    head:
      entity: light.bedroom_tablelights
      name: Tablelights
    type: custom:fold-entity-row
  type: entities
columns: 1
square: false
title: Lights
type: grid
