---
baseoid: 1.3.6.1.2.1.105.1.1.1.3.1.25
community: !secret snmp_community
host: mel-switch-1.alfa.illallangi.enterprises
name: Office Google Mini
payload_off: 2
payload_on: 1
platform: snmp
version: 2c
