---
action:
- data:
    brightness_step_pct: -25
    color_temp: 500
  service: light.turn_on
  target:
    entity_id:
    - light.bedroom_tablelight_1
    - light.bedroom_tablelight_2
alias: bedroom-controller-tablelights-down
mode: single
trigger:
- entity_id:
  - sensor.bedroom_controller_action
  from: button_1_single
  platform: state
  to: ""
