---
action:
- service: light.turn_off
  target:
    entity_id:
    - light.bedroom_downlights
alias: bedroom-controller-downlights-off
mode: single
trigger:
- entity_id:
  - sensor.bedroom_controller_action
  from: button_3_double
  platform: state
  to: ""
