---
action:
- data:
    hvac_mode: cool
  service: climate.set_hvac_mode
  target:
    entity_id: climate.bedroom_hvac
- data:
    hvac_mode: cool
    temperature: 21
  service: climate.set_temperature
  target:
    entity_id: climate.bedroom_hvac
- service: climate.turn_on
  target:
    entity_id: climate.bedroom_hvac
- data:
    fan_mode: Auto
  service: climate.set_fan_mode
  target:
    entity_id: climate.bedroom_hvac
- data:
    swing_mode: vertical
  service: climate.set_swing_mode
alias: bedroom-controller-hvac-on
condition:
- condition: state
  entity_id: binary_sensor.bedroom_door_terrace_contact
  state: "off"
mode: single
trigger:
- entity_id:
  - sensor.bedroom_controller_action
  from: button_6_single
  platform: state
  to: ""
