---
action:
- data:
    brightness_step_pct: 25
    color_temp: 500
  service: light.turn_on
  target:
    entity_id:
    - light.bedroom_downlight_1
    - light.bedroom_downlight_2
alias: bedroom-controller-downlight-up
mode: single
trigger:
- entity_id:
  - sensor.bedroom_controller_action
  from: button_4_single
  platform: state
  to: ""
