---
action:
- data:
    brightness_pct: 100
    color_temp: 500
  service: light.turn_on
  target:
    entity_id:
    - light.bedroom_downlight_1
    - light.bedroom_downlight_2
alias: bedroom-controller-downlight-on
mode: single
trigger:
- entity_id:
  - sensor.bedroom_controller_action
  from: button_4_double
  platform: state
  to: ""
