---
action:
- service: light.turn_on
  target:
    entity_id:
    - light.bedroom_downlights
alias: bedroom-controller-downlights-on
mode: single
trigger:
- entity_id:
  - sensor.bedroom_controller_action
  from: button_4_double
  platform: state
  to: ""
