---
cards:
- entity: climate.kitchen_hvac
  type: thermostat
- entities:
  - entity: sensor.kitchen_temperature
    name: Temperature
  - entity: sensor.kitchen_humidity
    name: Humidity
  type: entities
columns: 1
square: false
title: Climate
type: grid
