---
cards:
- entity: climate.kitchen_hvac
  type: thermostat
- entities:
  - sensor.kitchen_humidity
  - sensor.kitchen_temperature
  type: entities
columns: 1
square: false
title: Climate
type: grid
