---
platform: template
sensors:
  office_downlight_3_power:
    device_class: power
    friendly_name: Office Downlight 3 Power
    unit_of_measurement: W
    value_template: "{{ (states('sensor.office_downlights_power') | float(0.0) / 4) }}"
