---
action:
- service: light.toggle
  target:
    entity_id: light.laundry_downlights
alias: Laundry Downlights
mode: single
trigger:
- entity_id: binary_sensor.laundry_switch_1
  from: "off"
  platform: state
  to: "on"
- entity_id: binary_sensor.laundry_switch_2
  from: "off"
  platform: state
  to: "on"
