---
platform: template
sensors:
  lounge_downlight_5_power:
    device_class: power
    friendly_name: Lounge Downlight 5 Power
    unit_of_measurement: W
    value_template: "{{ (states('sensor.lounge_downlights_power') | float(0.0) / 5) }}"
