---
cards:
- entities:
  - entity: sensor.driveway_climate_temperature
    name: Temperature
  - entity: sensor.driveway_climate_humidity
    name: Humidity
  type: entities
columns: 1
square: false
title: Climate
type: grid
