---
cards:
- entities:
  - entities:
    - entity: light.driveway_downlight_1
      name: Downlight 1
      secondary_info: "{{states('sensor.driveway_downlight_1_power')}} W"
      type: custom:secondaryinfo-entity-row
    head:
      entity: light.driveway_downlights
      name: Downlights
      secondary_info: "{{states('sensor.driveway_downlights_power')}} W"
      type: custom:secondaryinfo-entity-row
    type: custom:fold-entity-row
  type: entities
columns: 1
square: false
title: Lights
type: grid
