---
action:
- service: homeassistant.turn_off
  target:
    entity_id: switch.ensuite_fan
alias: Ensuite Fan Off
condition:
- condition: and
  conditions:
  - condition: not
    conditions:
      condition: state
      entity_id: light.ensuite_downlights
      state: "on"
mode: single
trigger:
- event: start
  platform: homeassistant
- entity_id: switch.ensuite_fan
  for:
    seconds: 1
  platform: state
  to: "on"
- entity_id:
  - light.ensuite_downlights
  for:
    seconds: 15
  platform: state
  to: "off"
