---
action:
- service: homeassistant.turn_on
  target:
    entity_id: light.ensuite_nightlights
alias: Ensuite Nightlights On
condition:
- condition: or
  conditions:
  - condition: state
    entity_id:
    - light.ensuite_downlights
    state: "on"
  - condition: state
    entity_id:
    - sun.sun
    state: below_horizon
mode: single
trigger:
- event: start
  platform: homeassistant
- entity_id:
  - light.ensuite_downlights
  platform: state
  to: "on"
- entity_id:
  - sun.sun
  platform: state
  to: below_horizon
