---
cards:
- entities:
  - entity: sensor.garage_temperature
    name: Temperature
  - entity: sensor.garage_humidity
    name: Humidity
  type: entities
columns: 1
square: false
title: Climate
type: grid
