---
platform: template
sensors:
  bedroom_downlights_power:
    device_class: power
    friendly_name: Bedroom Downlights Power
    unit_of_measurement: W
    value_template: >-
      {{
        (states('sensor.bedroom_downlight_1_power') | float(0.0)) +
        (states('sensor.bedroom_downlight_2_power') | float(0.0)) }}
