---
action:
- service: homeassistant.turn_on
  target:
    entity_id: light.driveway_downlights
alias: Driveway Downlights On
condition:
- condition: state
  entity_id:
  - sun.sun
  state: below_horizon
mode: single
trigger:
- event: start
  platform: homeassistant
- entity_id:
  - sun.sun
  platform: state
  to: below_horizon
