---
platform: template
sensors:
  stairwell_downlights_power:
    device_class: power
    friendly_name: Stairwell Downlights Power
    unit_of_measurement: W
    value_template: >-
      {{
        (states('sensor.stairwell_downlights_a_power') | float(0.0)) +
        (states('sensor.stairwell_downlight_3_power') | float(0.0)) +
        (states('sensor.stairwell_downlight_4_power') | float(0.0)) }}
