---
platform: template
sensors:
  stairwell_nightlight_2_power:
    device_class: power
    friendly_name: Stairwell Nightlight 2 Power
    unit_of_measurement: W
    value_template: "{{ (states('sensor.stairwell_nightlights_power') | float(0.0) / 6) }}"
