---
automation: !include_dir_list automations
# Loads default set of integrations. Do not remove.
default_config:
group: !include_dir_named groups
homeassistant:
  country: US
  currency: AUD
  elevation: !secret homeassistant_elevation
  external_url: https://homeassistant.illallangi.enterprises
  internal_url: https://homeassistant.illallangi.enterprises
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  name: Moonya Road
  time_zone: !secret homeassistant_timezone
  unit_system: metric
http:
  trusted_proxies:
  - 172.24.0.0/16
  - 10.0.0.0/8
  - 127.0.0.1
  - ::1
  use_x_forwarded_for: true
influxdb:
  api_version: 1
  database: !secret influxdb_database
  host: !secret influxdb_host
  port: !secret influxdb_port
  ssl: false
light: !include_dir_list lights
lovelace:
  mode: yaml
  resources:
  - type: module
    url: /local/card-tools.js
  - type: module
    url: /local/fold-entity-row.js
  - type: module
    url: /local/secondaryinfo-entity-row.js
recorder:
  db_url: !secret recorder_db_url
scene:
script:
sensor: !include_dir_list sensors
switch: !include_dir_list switches
template:
- sensor: !include_dir_list templates/sensor
tts:
- platform: google_translate