---
group: !include_dir_named groups
homeassistant:
light: !include_dir_list lights
lovelace:
  mode: yaml
  resources:
  - type: module
    url: /local/card-tools.js
  - type: module
    url: /local/fold-entity-row.js
  - type: module
    url: /local/secondaryinfo-entity-row.js
scene:
script:
sensor: !include_dir_list sensors
switch: !include_dir_list switches
template:
- sensor: !include_dir_list templates/sensor
tts:
- platform: google_translate