---
platform: template
sensors:
  ensuite_downlight_1_power:
    device_class: power
    friendly_name: Ensuite Downlight 1 Power
    unit_of_measurement: W
    value_template: "{{ (states('sensor.ensuite_downlights_power') | float(0.0) / 1) }}"
