---
platform: template
sensors:
  ensuite_downlights_power:
    device_class: power
    friendly_name: Ensuite Downlights Power
    unit_of_measurement: W
    value_template: >-
      {{
        (states('sensor.ensuite_downlight_1_power') | float(0.0)) }}
