---
action:
- data:
    transition: 0
  service: light.turn_off
  target:
    entity_id: light.garage_fluros
alias: door-garage-closed-garage-fluros-off
mode: single
trigger:
- entity_id:
  - binary_sensor.entrance_door_garage_contact
  for:
    seconds: 10
  platform: state
  to: "off"
