---
action:
- service: light.toggle
  target:
    entity_id: light.entrance_downlights
alias: Switch - Entrance Downlights
mode: single
trigger:
- entity_id: binary_sensor.entrance_switch_1
  from: "off"
  platform: state
  to: "on"
