---
platform: template
sensors:
  backyard_downlights_power:
    device_class: power
    friendly_name: Backyard Downlights Power
    unit_of_measurement: W
    value_template: >-
      {{
        (states('sensor.backyard_downlight_1_power') | float(0.0)) +
        (states('sensor.backyard_downlight_2_power') | float(0.0)) }}
