---
platform: template
sensors:
  bathroom_downlight_1_power:
    device_class: power
    friendly_name: Bathroom Downlight 1 Power
    unit_of_measurement: W
    value_template: "{{ (states('sensor.bathroom_downlights_power') | float(0.0) / 1) }}"
