---
cards:
- entity: climate.office_hvac
  type: thermostat
- entities:
  - entity: sensor.office_climate_temperature
    name: Temperature
  - entity: sensor.office_climate_humidity
    name: Humidity
  type: entities
columns: 1
square: false
title: Climate
type: grid
