---
entities:
- entity: binary_sensor.bedroom_blanket-left_status
  name: bedroom-blanket-left
- entity: binary_sensor.bedroom_blanket-right_status
  name: bedroom-blanket-right
- entity: binary_sensor.bedroom_dht_status
  name: bedroom-dht
- entity: binary_sensor.bedroom_hvac_status
  name: bedroom-hvac
- entity: binary_sensor.bedroom_shelly_1_status
  name: bedroom-shelly-1
- entity: binary_sensor.bedroom_shelly_2_status
  name: bedroom-shelly-2
- entity: binary_sensor.bedroom_tablelight-1_status
  name: bedroom-tablelight-1
- entity: binary_sensor.bedroom_tablelight-2_status
  name: bedroom-tablelight-2
show_header_toggle: false
title: Bedroom
type: entities
