---
entities:
- entity: binary_sensor.bedroom_blanket_left_status
  name: blanket-left
- entity: binary_sensor.bedroom_blanket_right_status
  name: blanket-right
- entity: binary_sensor.bedroom_dht_status
  name: dht
- entity: binary_sensor.bedroom_hvac_status
  name: hvac
- entity: binary_sensor.bedroom_shelly_1_status
  name: shelly-1
- entity: binary_sensor.bedroom_shelly_2_status
  name: shelly-2
- entity: binary_sensor.bedroom_tablelight_1_status
  name: tablelight-1
- entity: binary_sensor.bedroom_tablelight_2_status
  name: tablelight-2
title: Bedroom
type: history-graph
