---
entities:
- entity: binary_sensor.ensuite_shelly_1_status
  name: ensuite-shelly-1
- entity: binary_sensor.ensuite_shelly_2_status
  name: ensuite-shelly-2
show_header_toggle: false
title: Ensuite
type: entities
