---
entities:
- entity: binary_sensor.garage_dht_status
  name: dht
- entity: binary_sensor.garage_network_rack_status
  name: network-rack
- entity: binary_sensor.garage_server_rack_status
  name: server-rack
- entity: binary_sensor.garage_shelly_1_status
  name: shelly-1
- entity: binary_sensor.garage_shelly_2_status
  name: shelly-2
hours_to_show: 1
title: Garage
type: history-graph
