---
entities:
- entity: binary_sensor.laundry_dht_status
  name: dht
- entity: binary_sensor.laundry_dryer_status
  name: dryer
- entity: binary_sensor.laundry_shelly_1_status
  name: shelly-1
- entity: binary_sensor.laundry_shelly_2_status
  name: shelly-2
- entity: binary_sensor.laundry_washer_status
  name: washer
title: Laundry
type: history-graph
