---
entities:
- entity: binary_sensor.lounge_downlight_1_status
  name: downlight-1
- entity: binary_sensor.lounge_downlight_2_status
  name: downlight-2
- entity: binary_sensor.lounge_downlight_3_status
  name: downlight-3
- entity: binary_sensor.lounge_downlight_4_status
  name: downlight-4
- entity: binary_sensor.lounge_downlight_5_status
  name: downlight-5
- entity: binary_sensor.lounge_hvac_status
  name: hvac
- entity: binary_sensor.lounge_shelly_status
  name: shelly
- entity: binary_sensor.lounge_tablelight_1_status
  name: tablelight-1
- entity: binary_sensor.lounge_tablelight_2_status
  name: tablelight-2
- entity: binary_sensor.lounge_tablelight_3_status
  name: tablelight-3
- entity: binary_sensor.lounge_tablelight_4_status
  name: tablelight-4
title: Lounge
type: history-graph
