---
entities:
- entity: binary_sensor.office_downlight-1_status
  name: office-downlight-1
- entity: binary_sensor.office_downlight-2_status
  name: office-downlight-2
- entity: binary_sensor.office_downlight-3_status
  name: office-downlight-3
- entity: binary_sensor.office_downlight-4_status
  name: office-downlight-4
- entity: binary_sensor.office_hvac_status
  name: office-hvac
- entity: binary_sensor.office_rack_status
  name: office-rack
- entity: binary_sensor.office_shelly_1_status
  name: office-shelly-1
- entity: binary_sensor.office_shelly_2_status
  name: office-shelly-2
- entity: binary_sensor.office_tablelight-1_status
  name: office-tablelight-1
- entity: binary_sensor.office_tablelight-2_status
  name: office-tablelight-2
show_header_toggle: false
title: Office
type: entities
