---
entities:
- entity: binary_sensor.office_downlight_1_status
  name: downlight-1
- entity: binary_sensor.office_downlight_2_status
  name: downlight-2
- entity: binary_sensor.office_downlight_3_status
  name: downlight-3
- entity: binary_sensor.office_downlight_4_status
  name: downlight-4
- entity: binary_sensor.office_hvac_status
  name: hvac
- entity: binary_sensor.office_rack_status
  name: rack
- entity: binary_sensor.office_shelly_1_status
  name: shelly-1
- entity: binary_sensor.office_shelly_2_status
  name: shelly-2
- entity: binary_sensor.office_tablelight_1_status
  name: tablelight-1
- entity: binary_sensor.office_tablelight_2_status
  name: tablelight-2
hours_to_show: 1
title: Office
type: history-graph
