---
entities:
- entity: binary_sensor.stairwell_shelly_1_status
  name: shelly-1
- entity: binary_sensor.stairwell_shelly_2_status
  name: shelly-2
- entity: binary_sensor.stairwell_shelly_3_status
  name: shelly-3
title: Stairwell
type: history-graph
