---
cards:
- entity: binary_sensor.lounge_door_stairwell_contact
  name: Stairwell Door
- entity: binary_sensor.lounge_door_terrace_contact
  name: Terrace Door
columns: 1
square: false
title: Security
type: grid
