---
cards:
- entities:
  - entity: switch.bathroom_fan
    name: Fan
    secondary_info: "{{states('sensor.bathroom_fan_power')}} W"
    type: custom:secondaryinfo-entity-row
  - entity: sensor.bathroom_humidity
  - entity: sensor.bathroom_temperature
  type: entities
columns: 1
square: false
title: Climate
type: grid
