---
cards:
- entities:
  - entities:
    - entity: light.bathroom_downlight_1
      name: Downlight 1
      secondary_info: "{{states('sensor.bathroom_downlight_1_power')}} W"
      type: custom:secondaryinfo-entity-row
    head:
      entity: light.bathroom_downlights
      name: Downlights
      secondary_info: "{{states('sensor.bathroom_downlights_power')}} W"
      type: custom:secondaryinfo-entity-row
    type: custom:fold-entity-row
  - entities:
    - entity: light.bathroom_nightlight_1
      name: Nightlight 1
      secondary_info: "{{states('sensor.bathroom_nightlight_1_power')}} W"
      type: custom:secondaryinfo-entity-row
    head:
      entity: light.bathroom_nightlights
      name: Nightlights
      secondary_info: "{{states('sensor.bathroom_nightlights_power')}} W"
      type: custom:secondaryinfo-entity-row
    type: custom:fold-entity-row
  type: entities
columns: 1
square: false
title: Lights
type: grid
