---
platform: template
sensors:
  kitchen_downlight_10_power:
    device_class: power
    friendly_name: Kitchen Downlight 10 Power
    unit_of_measurement: W
    value_template: "{{ (states('sensor.kitchen_downlights_a_power') | float(0.0) / 6) }}"
