---
platform: template
sensors:
  kitchen_downlight_11_power:
    device_class: power
    friendly_name: Kitchen Downlight 11 Power
    unit_of_measurement: W
    value_template: "{{ (states('sensor.kitchen_downlights_c_power') | float(0.0) / 2) }}"
