---
platform: template
sensors:
  kitchen_downlights_power:
    device_class: power
    friendly_name: Kitchen Downlights Power
    unit_of_measurement: W
    value_template: >-
      {{
        (states('sensor.kitchen_downlights_a_power') | float(0.0)) +
        (states('sensor.kitchen_downlights_b_power') | float(0.0)) +
        (states('sensor.kitchen_downlights_c_power') | float(0.0)) }}
