---
platform: template
sensors:
  kitchen_downlight_07_power:
    device_class: power
    friendly_name: Kitchen Downlight 07 Power
    unit_of_measurement: W
    value_template: "{{ (states('sensor.kitchen_downlights_b_power') | float(0.0) / 4) }}"
